retriever_config:
  stop_tokens: ["<|start_header_id|>","<|end_header_id|>","<|eot_id|>"]
  experience_schema: "{
    'roleName': The job role occupied,
    'companyName': The campany name,
    'location': The location of the company,
    'datePeriod': The period of the experience divided by a '-' ( if the end date does not exist then write 'Present') it is required,
  }"

  experience_content_schema: "{
    'accomplishments': A list accomplishements provided in the query ( strings ),
    'skills': A list of skills present or can be derived from the query
  }"

  experience_extraction_prompt: "You are data engineer working in a recruitment department.
    You take a prompt of professional experiences in a job and you extract, based on a
    schema, the required information. Make sure to reformulate the accomplishements, when needed and if present in the schema, by adding action verbs,
    highlighting the contributions, and keeping metrics if present. No preambles and return a correct JSON format with no nulls.
    
    Schema: {schema}
    
    Experience: {query}"

  experience_construct_prompt: "You are a professionnal writer. You take a structures JSON format
    related to the {section_name} section and reconstruct it into the appropriate block format
    for the resume. No preambles and no extra details

    JSON to reconstruct: {json_text}"

generater_config:
  stop_tokens: ["<|start_header_id|>","<|end_header_id|>","<|eot_id|>"]
  experience_filter_prompt: "As a job seeker, you take in a job offer below and you read it thoroughly. You look for
    information usefull to determine the experiences, the tasks and tools/technologies needed for this position and you write them in a single 
    small paragraph with no preambles.
    
    Job Offer: {job_offer}"
  softskills_filter_prompt: "As a job seeker, you take in a job offer below and you read it thoroughly. You look for
    information usefull to determine the softskill required from the candidate for this position and what the company 
    values the most. You write what you found in a single small paragraph with no preambles.
  
    Job Offer: {job_offer}"                             
  generator_prompt: "As a professional writer in a job search company, you help candidates to write a good resume to 
    apply for their dream job. They provide you with the softskills and experiences needed for the job whilist you add
    their relevant expereinces to filter more. Then you finally write a resumer with their fullname, phone number, email,
    education, skills, and their professional experiences. The resumer should follow the canadian style. If needed remove unneded
    information and make it coherent. Use the softskills in the summary.
    
    Fullname: {fullName}
    Phone Number: {phoneNumber}
    Email: {email}
    Education:{education}
    Softskills: {softSkills}
    Professional experiences needed:{experiences_company}
    Professional experiences candidate: {experience_context}"
